// config/roles.js

export const ROLES = {
  ADMIN: 'admin',
  TEACHER: 'teacher',
  PARENT: 'parent',
};

export const PERMISSIONS = {
  CREATE_STUDENT: 'create:student',
  READ_STUDENT: 'read:student',
  UPDATE_STUDENT: 'update:student',
  DELETE_STUDENT: 'delete:student',
  MANAGE_USERS: 'manage:users',
  
  // Permisos para artículos
  CREATE_ARTICLE: 'create:article',
  READ_ARTICLE: 'read:article',
  UPDATE_ARTICLE: 'update:article',
  DELETE_ARTICLE: 'delete:article',
  // ... otros permisos
};

export const ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: [
    PERMISSIONS.CREATE_STUDENT,
    PERMISSIONS.READ_STUDENT,
    PERMISSIONS.UPDATE_STUDENT,
    PERMISSIONS.DELETE_STUDENT,
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.CREATE_ARTICLE,
    PERMISSIONS.READ_ARTICLE,
    PERMISSIONS.UPDATE_ARTICLE,
    PERMISSIONS.DELETE_ARTICLE,
  ],
  [ROLES.TEACHER]: [
    PERMISSIONS.CREATE_STUDENT,
    PERMISSIONS.READ_STUDENT,
    PERMISSIONS.UPDATE_STUDENT,
    PERMISSIONS.CREATE_ARTICLE,
    PERMISSIONS.READ_ARTICLE,
    PERMISSIONS.UPDATE_ARTICLE,
  ],
  [ROLES.PARENT]: [
    PERMISSIONS.READ_STUDENT,
    PERMISSIONS.READ_ARTICLE,
  ],
};
